# Generated by Django 6.0.3 on 2026-04-07 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='teacher',
        ),
        migrations.AddField(
            model_name='mark',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass'),
        ),
    ]
