# Generated by Django 6.0.3 on 2026-04-08 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_mark_teacher_mark_school_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='mark',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.academicterm'),
            preserve_default=False,
        ),
    ]
